from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any

try:
    import rclpy
    from rclpy.node import Node
    from sensor_msgs.msg import Image
except ModuleNotFoundError:  # pragma: no cover - local unit tests stub ROS.
    rclpy = None  # type: ignore[assignment]
    Node = object  # type: ignore[misc,assignment]
    Image = object  # type: ignore[misc,assignment]


def camera_info_yaml(
    *,
    width: int,
    height: int,
    camera_name: str,
    camera_matrix: list[float],
    distortion_coefficients: list[float],
    rectification_matrix: list[float],
    projection_matrix: list[float],
) -> str:
    return "\n".join(
        [
            "# Measured Camera Module 3 calibration generated by vexy_calibrate_camera.",
            f"image_width: {width}",
            f"image_height: {height}",
            f"camera_name: {camera_name}",
            "camera_matrix:",
            "  rows: 3",
            "  cols: 3",
            f"  data: [{_numbers(camera_matrix)}]",
            "distortion_model: plumb_bob",
            "distortion_coefficients:",
            "  rows: 1",
            f"  cols: {len(distortion_coefficients)}",
            f"  data: [{_numbers(distortion_coefficients)}]",
            "rectification_matrix:",
            "  rows: 3",
            "  cols: 3",
            f"  data: [{_numbers(rectification_matrix)}]",
            "projection_matrix:",
            "  rows: 3",
            "  cols: 4",
            f"  data: [{_numbers(projection_matrix)}]",
            "",
        ]
    )


def _numbers(values: list[float]) -> str:
    return ", ".join(f"{float(value):.12g}" for value in values)


class CheckerboardCalibrator(Node):  # type: ignore[misc,valid-type]
    def __init__(self, args: argparse.Namespace) -> None:
        if rclpy is None:
            raise RuntimeError("rclpy is required; run this inside the ROS 2 runtime")
        super().__init__("vexy_camera_calibrator")
        self.args = args
        self.image_points: list[Any] = []
        self.object_points: list[Any] = []
        self.image_size: tuple[int, int] | None = None
        self.last_capture_s = 0.0
        self.frames_seen = 0
        self.frames_with_board = 0
        self.preview_dir = args.preview_dir
        if self.preview_dir is not None:
            self.preview_dir.mkdir(parents=True, exist_ok=True)
        self.create_subscription(Image, args.image_topic, self._on_image, 10)
        self.get_logger().info(
            f"watching {args.image_topic} for {args.cols}x{args.rows} checkerboard; "
            "move the board through the frame"
        )

    @property
    def complete(self) -> bool:
        return len(self.image_points) >= self.args.samples

    def _on_image(self, msg: Image) -> None:
        import cv2
        import numpy as np

        self.frames_seen += 1
        gray = image_msg_to_gray(msg)
        pattern_size = (self.args.cols, self.args.rows)
        found, corners = cv2.findChessboardCorners(gray, pattern_size)
        if not found:
            return
        self.frames_with_board += 1
        now_s = time.monotonic()
        if now_s - self.last_capture_s < self.args.min_interval_s:
            return

        criteria = (
            cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,
            30,
            0.001,
        )
        refined = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        self.image_size = (int(msg.width), int(msg.height))
        self.image_points.append(refined)
        self.object_points.append(checkerboard_object_points(args=self.args, np=np))
        self.last_capture_s = now_s
        sample_count = len(self.image_points)
        self.get_logger().info(
            f"captured checkerboard sample {sample_count}/{self.args.samples}"
        )
        if self.preview_dir is not None:
            preview = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
            cv2.drawChessboardCorners(preview, pattern_size, refined, found)
            cv2.imwrite(
                str(self.preview_dir / f"sample_{sample_count:03d}.jpg"), preview
            )

    def calibrate_and_write(self) -> None:
        import cv2
        import numpy as np

        if self.image_size is None or not self.image_points:
            raise RuntimeError("no checkerboard samples were captured")
        rms, k, d, rvecs, tvecs = cv2.calibrateCamera(
            self.object_points,
            self.image_points,
            self.image_size,
            None,
            None,
        )
        _ = rvecs, tvecs
        rectification = np.eye(3, dtype=np.float64)
        projection = np.zeros((3, 4), dtype=np.float64)
        projection[:3, :3] = k
        text = camera_info_yaml(
            width=self.image_size[0],
            height=self.image_size[1],
            camera_name=self.args.camera_name,
            camera_matrix=k.reshape(-1).tolist(),
            distortion_coefficients=d.reshape(-1).tolist(),
            rectification_matrix=rectification.reshape(-1).tolist(),
            projection_matrix=projection.reshape(-1).tolist(),
        )
        self.args.out.parent.mkdir(parents=True, exist_ok=True)
        self.args.out.write_text(text)
        self.get_logger().info(
            f"wrote {self.args.out} from {len(self.image_points)} samples; "
            f"rms reprojection error {rms:.4f}"
        )


def checkerboard_object_points(*, args: argparse.Namespace, np: Any) -> Any:
    objp = np.zeros((args.rows * args.cols, 3), np.float32)
    grid = np.mgrid[0 : args.cols, 0 : args.rows].T.reshape(-1, 2)
    objp[:, :2] = grid * float(args.square_m)
    return objp


def image_msg_to_gray(msg: Image) -> Any:
    import cv2
    import numpy as np

    encoding = str(msg.encoding).lower()
    data = np.frombuffer(msg.data, dtype=np.uint8)
    if encoding == "mono8":
        return data.reshape((msg.height, msg.step))[:, : msg.width]
    if encoding in {"rgb8", "bgr8", "rgba8", "bgra8"}:
        channels = 4 if encoding in {"rgba8", "bgra8"} else 3
        image = data.reshape((msg.height, msg.step // channels, channels))[
            :, : msg.width, :
        ]
        code_by_encoding = {
            "rgb8": cv2.COLOR_RGB2GRAY,
            "bgr8": cv2.COLOR_BGR2GRAY,
            "rgba8": cv2.COLOR_RGBA2GRAY,
            "bgra8": cv2.COLOR_BGRA2GRAY,
        }
        code = code_by_encoding[encoding]
        return cv2.cvtColor(image, code)
    if encoding in {"yuv422", "yuyv", "yuyv422"}:
        image = data.reshape((msg.height, msg.step // 2, 2))[:, : msg.width, :]
        return cv2.cvtColor(image, cv2.COLOR_YUV2GRAY_YUY2)
    raise ValueError(f"unsupported image encoding: {msg.encoding!r}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Headless checkerboard calibration for the vexy Pi camera."
    )
    parser.add_argument("--image-topic", default="/camera/image_raw")
    parser.add_argument("--cols", type=int, default=8)
    parser.add_argument("--rows", type=int, default=6)
    parser.add_argument("--square-m", type=float, default=0.025)
    parser.add_argument("--samples", type=int, default=25)
    parser.add_argument("--timeout-s", type=float, default=180.0)
    parser.add_argument("--min-interval-s", type=float, default=0.35)
    parser.add_argument("--camera-name", default="imx708_wide")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("/home/vexy/calibration/imx708_wide_640x480.yaml"),
    )
    parser.add_argument("--preview-dir", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.cols <= 0 or args.rows <= 0:
        print("cols and rows must be positive", file=sys.stderr)
        return 2
    if args.square_m <= 0:
        print("square-m must be positive", file=sys.stderr)
        return 2
    if args.samples <= 2:
        print("samples must be greater than 2", file=sys.stderr)
        return 2
    if rclpy is None:
        print("rclpy is required; source the ROS 2 workspace first", file=sys.stderr)
        return 1

    rclpy.init()
    node = CheckerboardCalibrator(args)
    deadline_s = time.monotonic() + args.timeout_s
    try:
        while not node.complete and time.monotonic() < deadline_s:
            rclpy.spin_once(node, timeout_sec=0.05)
        if not node.complete:
            print(
                "calibration timed out after "
                f"{args.timeout_s:.1f}s; captured {len(node.image_points)}/"
                f"{args.samples} samples from {node.frames_seen} frames "
                f"({node.frames_with_board} with checkerboard)",
                file=sys.stderr,
            )
            return 1
        node.calibrate_and_write()
    finally:
        node.destroy_node()
        rclpy.shutdown()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
